// Query key constants for better maintainability and type safety

// Settings
export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SYSTEM_INFO = 'GET_SYSTEM_INFO';
export const GET_STORAGE_USAGE = 'GET_STORAGE_USAGE';
export const GET_BACKUPS = 'GET_BACKUPS';
export const GET_LOGS = 'GET_LOGS';

// Categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_BASIC_CATEGORIES = 'GET_BASIC_CATEGORIES';
export const GET_CLINICAL_CATEGORIES = 'GET_CLINICAL_CATEGORIES';
export const GET_CATEGORY_STATS = 'GET_CATEGORY_STATS';
export const GET_ACTIVE_CATEGORY_NAMES = 'GET_ACTIVE_CATEGORY_NAMES';

// Intakes
export const GET_INTAKES = 'GET_INTAKES';
export const GET_INTAKE = 'GET_INTAKE';
export const GET_INTAKES_OPTIONS = 'GET_INTAKES_OPTIONS';

// Questions
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTION_STATISTICS = 'GET_QUESTION_STATISTICS';
export const GET_QUESTION_CATEGORIES = 'GET_QUESTION_CATEGORIES';
export const GET_QUESTION_YEARS = 'GET_QUESTION_YEARS';
export const GET_QUESTION_INTAKES = 'GET_QUESTION_INTAKES';
export const GET_RECENT_QUESTIONS = 'GET_RECENT_QUESTIONS';
export const GET_QUESTIONS_BY_CATEGORY = 'GET_QUESTIONS_BY_CATEGORY';
export const GET_QUESTIONS_BY_YEAR = 'GET_QUESTIONS_BY_YEAR';
export const GET_QUESTIONS_BY_INTAKE = 'GET_QUESTIONS_BY_INTAKE';
export const GET_QUESTIONS_BY_STATUS = 'GET_QUESTIONS_BY_STATUS';

// Extraction
export const GET_EXTRACTION_STATUS = 'GET_EXTRACTION_STATUS';
export const GET_EXTRACTION_STATISTICS = 'GET_EXTRACTION_STATISTICS';
export const GET_QUEUE_STATUS = 'GET_QUEUE_STATUS';
export const GET_PDF_INFO = 'GET_PDF_INFO';
export const GET_OLLAMA_HEALTH = 'GET_OLLAMA_HEALTH';
export const GET_VALIDATION = 'GET_VALIDATION';
export const GET_EXTRACTION_SUMMARY = 'GET_EXTRACTION_SUMMARY';
export const GET_PDFS = 'GET_PDFS';
export const GET_EXTRACTION_LOGS = 'GET_EXTRACTION_LOGS';
